clone:
  depth: full
pipelines:
  branches:
    main:
      - step:
          name: Clone to GitHub
          script:
            - git remote add upstream git@github.com:dataforgelabs/terraform-azure-databricks-starter.git
            - git push --force upstream $BITBUCKET_BRANCH